### ISSUE TITLE
帖子时间显示问题和头像问题

### ISSUE THREAD

**Issue by antct** [Deturium/CC98-PWA#40]
按照最新的代码部署了一下，版本号是1.7.0。

1. 看之前的issue， #35 ，似乎在个人信息页显示发表主题的时候还是会出现锁沉帖子的显示问题。

2. 加载头像时，似乎每次无限加载拉取新的回复列表时，只会加载列表内的第一个头像。。这个问题我存疑，，可能是我这边造成的。

**Comment by Tsukiko15** [comment]
公开版面被锁沉的帖子会出现在个人信息，被删除的帖子才不会。

**Comment by antct** [comment]
> 公开版面被锁沉的帖子会出现在个人信息，被删除的帖子才不会。

不是这个意思，是时间的显示问题，类似于 #35 ，只不过是在个人信息页面的。
